### ISSUE TITLE
Object detection 

### ISSUE THREAD

**Issue by Ranjitha115** [beingaryan/Blind-Assistance-Object-Detection-and-Navigation#4]
**can you please tell me how to install Packages and what tools are you used.In you tube the video is not clear i am not able to follow that can you please suggest me**Please help me

**Comment by beingaryan** [comment]
You can download packages manually by hitting up the commands!
You can refer to this for NumPy-based Library!
`pip install numpy`
Similarly, you can try other libraries too!

**Comment by Ranjitha115** [comment]
I am getting protoc error.. protoc is not converting to python file..will u
suggest me

**Comment by beingaryan** [comment]
Share the error here.

**Comment by Ranjitha115** [comment]
[](url)
